version: "3.8"
x-dela: &dela
  image: ghcr.io/c4dt/d-voting-dela:latest
  environment:
    PROXYKEY: ${PUBLIC_KEY}
    PROXYPORT: ${PROXYPORT}
    PROXY_LOG: info
    LLVL: info
    NODEPORT: ${NODEPORT}

services:

  dela-worker-0:             # inital DELA leader node
    <<: *dela
    build:
      dockerfile: Dockerfiles/Dockerfile.dela
      context: ../
      target: production
    volumes:
      - dela-worker-0-data:/data
    hostname: dela-worker-0
    networks:
      d-voting:
        ipv4_address: 172.19.44.254
  dela-worker-1:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-1-data:/data
    hostname: dela-worker-1
    networks:
      d-voting:
        ipv4_address: 172.19.44.253
  dela-worker-2:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-2-data:/data
    hostname: dela-worker-2
    networks:
      d-voting:
        ipv4_address: 172.19.44.252
  dela-worker-3:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-3-data:/data
    hostname: dela-worker-3
    networks:
      d-voting:
        ipv4_address: 172.19.44.251

  frontend:         # web service frontend
    image: ghcr.io/c4dt/d-voting-frontend:latest
    build:
      dockerfile: Dockerfiles/Dockerfile.frontend
      context: ../
    ports:
      - 127.0.0.1:3000:3000
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      d-voting:
        ipv4_address: 172.19.44.2

  backend:          # web service backend
    image: ghcr.io/c4dt/d-voting-backend:latest
    build:
      dockerfile: Dockerfiles/Dockerfile.backend
      context: ../
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DB_PATH: /data/${DB_PATH}
      FRONT_END_URL: ${FRONT_END_URL}
      DELA_NODE_URL: ${DELA_NODE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PUBLIC_KEY: ${PUBLIC_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      db:
        condition: service_started
    volumes:
      - backend-data:/data
    networks:
      d-voting:
        ipv4_address: 172.19.44.3

  db:               # PostgreSQL database
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../web/backend/src/migration.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      d-voting:
        ipv4_address: 172.19.44.4

volumes:
  postgres-data:    # PostgreSQL database
  dela-worker-0-data:
  dela-worker-1-data:
  dela-worker-2-data:
  dela-worker-3-data:
  dela-worker-4-data:
  backend-data:

networks:
  d-voting:
    ipam:
      config:
        - subnet: 172.19.44.0/24
          gateway: 172.19.44.1
