version: "3.8"
x-dela: &dela
  image: ghcr.io/dedis/d-voting-dela:latest
  env_file: ../.env
x-dela-env: &dela-env
  PROXYKEY: ${PUBLIC_KEY}
  PROXY_LOG: info
  LLVL: info

services:

  dela-worker-0:             # inital DELA leader node
    <<: *dela
    build:
      dockerfile: Dockerfiles/Dockerfile.dela
      context: ../
      target: build
    environment:
      <<: *dela-env
      PUBLIC_URL: grpc://dela-worker-0:2000
    volumes:
      - dela-worker-0-data:/data
    networks:
      d-voting:
        ipv4_address: 172.19.44.254
  dela-worker-1:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-1-data:/data
    environment:
      <<: *dela-env
      PUBLIC_URL: grpc://dela-worker-1:2000
    networks:
      d-voting:
        ipv4_address: 172.19.44.253
  dela-worker-2:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-2-data:/data
    environment:
      <<: *dela-env
      PUBLIC_URL: grpc://dela-worker-2:2000
    networks:
      d-voting:
        ipv4_address: 172.19.44.252
  dela-worker-3:             # DELA worker node
    <<: *dela
    volumes:
      - dela-worker-3-data:/data
    environment:
      <<: *dela-env
      PUBLIC_URL: grpc://dela-worker-3:2000
    networks:
      d-voting:
        ipv4_address: 172.19.44.251

  frontend:         # web service frontend
    image: ghcr.io/dedis/d-voting-frontend:latest
    build:
      dockerfile: Dockerfiles/Dockerfile.frontend
      context: ../
    ports:
      - 127.0.0.1:3000:3000
    env_file: ../.env
    networks:
      d-voting:
        ipv4_address: 172.19.44.2

  backend:          # web service backend
    image: ghcr.io/dedis/d-voting-backend:latest
    build:
      dockerfile: Dockerfiles/Dockerfile.backend
      context: ../
    env_file: ../.env
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      db:
        condition: service_started
    volumes:
      - backend-data:/data
    networks:
      d-voting:
        ipv4_address: 172.19.44.3

  db:               # PostgreSQL database
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../web/backend/src/migration.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      d-voting:
        ipv4_address: 172.19.44.4

volumes:
  postgres-data:    # PostgreSQL database
  dela-worker-0-data:
  dela-worker-1-data:
  dela-worker-2-data:
  dela-worker-3-data:
  dela-worker-4-data:
  backend-data:

networks:
  d-voting:
    ipam:
      config:
        - subnet: 172.19.44.0/24
          gateway: 172.19.44.1
