FROM node:20-bookworm as build

ENV REACT_APP_PROXY=http://localhost:9081
ENV REACT_APP_NOMOCK=on
WORKDIR /web/frontend
COPY ../web/frontend .
RUN npm ci
RUN npm run build

FROM lipanski/docker-static-website:latest

COPY --from=build /web/frontend/build/ .

CMD ["/busybox", "httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]
