#!/bin/bash

paths=$1

source ${paths}
source ${network_config}

echo "Creating bridge ${bridge_iface} with IP address ${uk_gw} ..."
sudo brctl addbr "${bridge_iface}" || true
sudo ip "${bridge_iface}" "${uk_gw}"

echo "Starting KVM image connected to bridge interface ${bridge_iface} ..."
"${qemu_script}" -k "${kvm_image}" -e "${fs_mount}" -b "${bridge_iface}" -m 1024 -a "netdev.ipv4_addr=${uk_ip} netdev.ipv4_gw_addr=${uk_gw} netdev.ipv4_subnet_mask=255.255.255.0 -- ${uk_port}"
