name: Go Unit Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        
# TODO: https://github.com/dedis/d-voting/issues/392
#      - name: Run lint
#        run: make lint
#
      - name: Run vet
        run: make vet

      - name: Test all, except integration, with coverage
        run: |
          go test $(go list ./... | grep -v /integration)
